version: "3.8"

services:

  web:
    build: .               # Usar el Dockerfile de esta carpeta
    container_name: foro_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./foro:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: foro_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: foro
      MYSQL_DATABASE: db
      MYSQL_USER: foro
      MYSQL_PASSWORD: foro
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
